### Send POST request with json body : use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 10000
}

### Send POST request with json body : cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "b4fe87a0fc5e42cfa045770daad9a9f6",
  "accountNumber": "1000000001",
  "amount": 10000
}

### Send GET request with json body : query transaction
GET http://localhost:8080/transaction/aa2d6e6d4e7946e2bc7d52f3cca60d57