### Send POST request with json body : use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}

### Send POST request with json body : cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "f0f92a820294452e89b57d2061d85f09",
  "accountNumber": "1000000000",
  "amount": 1000
}

### Send GET request with json body : query transaction
GET http://localhost:8080/transaction/aa2d6e6d4e7946e2bc7d52f3cca60d57